---
title: All honours students
description: Here, we list Marine Palaeoecology Lab students and their research projects. Students are ordered by how recently they graduated from UQ.
toc: true
toc-title: Researchers
toc-location: left
---

## Ben Grier

[b.grier@uq.net.au](mailto:b.grier@uq.net.au)

*Assessing the extent of climate risk for marine fish species in Australasia*

Climate change is affecting species at individual, population, and species levels, and understanding a species’ risk is important for predicting possible responses and impacts. This study aims to use a variation of environmental niche modelling to understand suitable and potentially hazardous conditions for a species, allowing for different risk levels to be quantified. This investigation will generate standardised risk scores that can inform fisheries industry, management, and conservation at relevant spatial scales such as genetic populations, stocks and aquaculture sites.

## Kirsten Golding

[k.golding@uq.net.au](mailto:k.golding@uq.edu.au)

*Investigating the effects of the 2022 East Australian floods on coral Spatial & temporal dynamics in benthic community structure of highly disturbed Quandamooka Sea Country, SE Queensland Australia*

Urbanisation and climate change are putting hard substrate benthic marine communities under stress. Understanding how these communities respond to stress is an important foundation for managing highly disturbed seascapes. My honours research aims to investigate the spatial and temporal trends in hard substrate benthic community structure, using seasonal photogrammetric sampling within Quandamooka (Moreton Bay) during a period with flooding and thermal disturbances. This will provide insight into community resilience throughout the bay which may be useful in guiding management decisions.

## Sarah Hampson

[s.hampson@uq.net.au](mailto:s.hampson@uq.net.au)

*The emergence of taxonomic and functional novelty in global freshwater fish communities through the Anthropocene*

Anthropogenic pressures continue to impact and transform ecological systems. In response, ecological communities are shifting towards unprecedented compositions, resulting in ecological novelty. Typically, novelty is studied based on taxonomic changes, whilst functional trait-based changes are largely ignored. My proposed study will apply a modern quantitative detection framework to a contemporary time series database to detect taxonomic and functional novelty in freshwater fish communities on a global scale. With this, I aim to better understand how trait changes contribute to novelty and determine whether considering community-level trait changes is beneficial for improving our understanding of ecological novelty.

## Joshua Wirth

[j.wirth@uq.net.au](mailto:j.wirth@uq.net.au)

*Investigating the effects of the 2022 East Australian floods on coral bleaching in Moreton Bay*

I am an undergraduate student with an interest in ecology currently undertaking my Honours in Ecology and Conservation Biology with the Paleoecology Lab. In my Honours project, I am looking at the effects of flood-induced sedimentation from the 2022 Eastern Australia Floods on the extent of coral bleaching in Moreton Bay, Australia. To do this, I am using a combination of photogrammetry and environmental data from coral reefs across the Bay to determine where coral bleaching has occurred, and when it has occurred relative to the floods and the onset of anomalously higher temperature conditions.

## Emer Cunningham

[e.cunningham@uqconnect.edu.au](mailto:e.cunningham@uqconnect.edu.au)

*Taxonomic and functional ecological novelty in coral communities along the Queensland coast during the past millennium*

Anthropogenic activities are driving rapid and unprecedented ecological turnover, resulting in novel community states. It is currently unclear how this novelty may extend beyond species turnover to affect the functional composition of communities. Through my honours research, I will provide a quantitative comparison of taxonomic and functional novelty in reef-building coral communities over the past millennium, spanning pre- and post-European invasion along the Queensland coast. This project will uncover the patterns and characteristics of past novel shifts and inform us of their potential future ecological consequences.

## Ellen Hall

[ellen.hall@uq.net.au](mailto:ellen.hall@uq.net.au)

*Long term ecological dynamics of coral communities in the Cape York peninsula*

The far north Queensland Coastline off the Cape York Peninsula has remained relatively untouched since European Colonisation. With a majority of land classed as nature conservation area, the Cape York Peninsula has been characterized by low sediment run-off, making it an ideal site for understanding reef community dynamics with limited influence from local anthropogenic stressors. This study aims to assess temporal changes in the coral reef community composition and accretion rates pre and post European settlement in an isolated local with limited anthropogenic influence. To date, limited research has been conducted on community composition within the isolated inshore reefs of the far northern GBR, making this study a unique look into reef persistence through time.

## Nina Clark

[nina.clark@uq.edu.au](mailto:nina.clark@uq.edu.au)

*Diversity and abundance of coral bioeroders across spatial and temporal gradients in water quality on the Great Barrier Reef.*

Since European colonisation of Queensland, the Great Barrier Reef (GBR) has been plagued with multiple external pressures. Modification of coastal habitats and intense agriculture resulted in increased runoff into adjacent rivers and estuarine waterways, subsequently polluting the GBR. This agricultural waste has caused eutrophication and terrigenous sedimentation, resulting in decreased water quality. In response to this, coral reefs have undergone rapid degradation. This project aims to investigate whether bioeroders have increased in abundance and diversity, both spatially and temporally, across a water quality gradient on the GBR, relative to anthropogenic perturbations. We expect to find that abundance and diversity of bioeroders increased with decreasing water quality, both through time as a result of European colonisation and across space as a result of nearshore proximity.

## Nicole Kyriacou

[n.kyriacou@uq.net.au](mailto:n.kyriacou@uq.net.au)

*Changes in community composition in subtropical corals in response to the 2016 coral bleaching event.*

This study will explore the changes in community composition in subtropical corals on the eastern Australian coastline in response to the recent coral bleaching event in 2016. The research will focus on coral community structure and coral mortality using data collected prior to, during, and after the coral bleaching event. The analysis of this data will: (1) evaluate the extent of damage among subtropical coral genera, (2) determine the relative sensitivity of coral genera to the recent coral bleaching event, and 3) quantify any changes in community structure (diversity and taxonomic composition) associated with the bleaching event. The findings of this study will further our understanding of expected changes within subtropical coral communities in response to climate change.

Nicole recently graduated from a Bachelor of Animal and Veterinary Biosciences (major in Zoology) at La Trobe University in Melbourne. Being an avid SCUBA diver in her leisure time, she fell in love with the Great Barrier Reef after completing part of her studies on Heron Island. Therefore, she decided to align her studies with her personal interests, and pursue honours in Marine Biology at UQ.

## Eleonora Fossile

[eleonora.fossile@gmail.com](mailto:eleonora.fossile@gmail.com)

*Reconstructing past phase shifts in coral reel Foraminifera communities using ancient DNA*

During my master’s thesis, I analysed living benthic Foraminifera assemblages in the Mediterranean Sea, using a taxonomical approach. I recognised species using morphological features and the composition of their test. However, during this internship, I had the opportunity to investigate the variation of Foraminifera biodiversity in the GBR with a completely different approach, using the environmental DNA. During the past three months, I worked alongside Karin Zwiep, undertaking many experiments to improve the protocol to extract aDNA from the sediment with the final aim to obtain the most realistic past assemblages. We evaluated several reference databases to analyse our aDNA and we also analysed sequence data looking at the Foraminifera genera level. Now I am almost at the end of this experience and I will go back to Europe to start my PhD (University of Angers (France) – Laboratoire d’études des Bio-Indicateurs Actuels et Fossiles). Unsurprisingly, I am delighted to continue my personal exploration of Foraminifera. Using a taxonomical approach, I will study modern and past Foraminifera communities from a completely different environment, the Arctic region. I will start this new experience enriched with knowledge and new skills that will certainly be useful for my future research career.

## Karin Zwiep

[k.zwiep@uq.edu.au](mailto:k.zwiep@uq.edu.au)

*The connection of coral symbiont genetic diversity between tropical and high latitude reefs*

The project I am currently working on aims to explore the genetic diversity of obligate coral symbionts present in high latitude coral communities, and compare this data against existing databases of coral-symbiont partnership diversity from nearby tropical Great Barrier Reef. The connection between tropical and high latitude reefs is particularly relevant as corals are predicted to move southward as oceans warm due to climate change. The results from this project are expected to provide information on the level of similarity, and thereby the long-term connectivity between high latitude and tropical coral communities.

## Samantha Eady

[samanthaeady@hotmail.com](mailto:samanthaeady@hotmail.com)

*Shifting baselines farther back: Ichthyoliths as palaeo-indicators of fish community structure throughout the Holocene from marginal reefs in Moreton Bay, Australia*

Anthropogenic impacts to coastal marine ecosystems have rapidly increased over the past decades in response to rapidly increasing population growth in coastal regions. In Moreton Bay (27º25`S, 152º20`E), Australia, commercial and recreational fishing activities have intensified since the onset of European settlement, nearly 200 years ago. However, the total impacts that these practices have had on fish communities are difficult to discern due to the lack of understanding of long-term historical baselines. To recognise the major drivers of ecological change and degradation of coastal marine ecosystems, whether natural and/or anthropogenic, requires an understanding of the baseline or natural conditions prior to any major anthropogenic exploitation. To determine the baseline conditions of fish community structure in a marine ecosystem, a useful ecological indicator is needed. This study uses microscopic fish teeth as a proxy to reconstruct the baseline structure of fish functional groups in Moreton Bay, Southeast Queensland, Australia, prior to and post European settlement. Fish teeth were picked from core and surface sediments from three sites across Moreton Bay (Wellington Point, Peel Island and Myora Reef) to analyse patterns in temporal and spatial scales of fish functional groups. We found a general increase in the number of fish teeth in more recent sediment samples, highlighting possible taphonomic (preservational) effects. No significant difference in fish community structure was observed among sites in Moreton Bay. However, a significant temporal change in the relative abundance of functional groups was observed: 1) between 0CE to 999CE and 1000CE to 1999CE; and 2) between 2000BCE to 1001BCE and 1000CE to 1999CE. Fishing activities in the past 2000 years in Moreton Bay appear to have had minimal impacts on the functional structure of fish communities; however, the impact of changing environmental conditions, resulting in variation in coral reef accretion, may be a likely factor influencing the changes in functional composition of fish communities through time.

## Kerrie Fraser

[k.fraser6@uq.edu.au](mailto:k.fraser6@uq.edu.au)

*Fishing for evidence: Has catch and effort in Moreton Bay’s recreational fishery been influenced by changing human dimensions and regulatory frameworks?*

Time-series of recreational fishing data are lacking for many parts of the world, despite longitudinal monitoring programs being regarded as essential to fisheries management. This study provides the first time-series comparison of catch and effort in Moreton Bay’s mixed-species recreational fishery, focusing on; Sillago maculata (diver whiting), Pagrus auratus (pink snapper), and Portunus armatus (blue swimmer crab). Access-point surveys were undertaken in Moreton Bay in 2013, and compared with surveys conducted using the same methodology in 1994/1995 and 1999. Diver whiting catch rates have significantly declined over the time-series, despite a regulatory change banning this species in commercial trawler bycatch, which was expected to increase productivity and catch rate. Snapper catch rates were consistent between 1994 and 2013, however a significantly greater catch rate in 1999 may have captured a ‘pulse’ increase in snapper abundance. Hyperstability could be occurring in this snapper fishery, with anglers potentially fishing down a declining stock. Size structure of snapper and diver whiting showed greater proportions in larger size classes in 2013 than past years, which for snapper is likely due to restrictive size limits. Mean length of the two species has significantly increased over time. Blue swimmer crabs showed opposite trends, with smaller proportions in larger size classes and a smaller mean carapace width in 2013. Human dimensions of these fisheries were examined in 2013, providing a baseline for future research. This study highlights the importance of time-series comparisons in identifying temporal trends, and may assist in sustainable management of recreational fisheries and fish stocks.

## Natalia Winkler

[nswinkle@uc.cl](mailto:nswinkle@uc.cl)

*Initial establishment of coral-Symbiodinium association*

Reef building corals (Scleractinian) generate habitat structural complexity that supports one of the most diverse marine ecosystems in the world, coral reefs. The success, productivity and growth of Scleractinian corals in oligotrophic tropical seas depends on the successful establishment of symbiosis between coral polyps and dinoflagellate symbionts, as they live in an obligate mutualistic association.

During the last year my field of interest has been the symbiotic association between Scleractinian corals and Symbiodinium dinoflagellates (zooxanthella), especially to understand the complex interactions occur between the holobiont (coral-symbiont) and the environment. This finely balanced symbiotic relationship is highly sensitive to changes in environmental conditions. As such my research has been focused in: (1) describe the environmental factors shaping the distribution Symbiodinium found in broadly distributed species along the Great Barrier Reef (GBR), and (2) evaluate if changes in symbiotic partnership facilitate shifts in thermal tolerance during the early onset of coral-Symbiodinium symbiosis for a common coral specie.

## Brent King 

[brent.king@uq.net.au](mailto:brent.king@uq.net.au)

*Calcification of the scleractinian coral Goniopora spp. on two inshore reefs of the Great Barrier Reef over the last millennium*

Seasonal density banding in coral skeletons offers a unique key to unravelling coral growth through time. Optical densitometry from x-radiographs will be used to calculate annual linear extension and skeletal density – thus calcification – of Goniopora spp. fragments from the coral reef matrix. This pre- industrial revolution baseline, extending back 1000 years, will allow analyses of past, present, and future relationships between environmental stressors and coral growth.

## Jack Coates-Marnane

[jack.coatesmarnane@uqconnect.edu.au](mailto:jack.coatesmarnane@uqconnect.edu.au)

*Rare earth element and heavy metal concentrations in growth bands of Favia speciosa and Plesiastrea versipora: investigating past environmental change and anthropogenic influence in Moreton Bay *

The marginal environments of Moreton Bay are strongly effected by terrestrial processes, with high annual river discharges and sediment loads, resulting in a typical estuarine type environment characterized by high turbidity. To explore the effects of both anthropogenic processes including, land-­use change, urban and industrial growth and natural process including ENSO, rainfall, weathering and sea level variation on the environments of Moreton Bay, the geochemical analyses of four massive corals from the bay was conducted. The geochemical analysis of annual growth bands of coral colonies of species Favia speciosa and Plesiastrea versipora using inductively coupled plasma mass spectrometry (ICP-­MS), allowed for the development of a proxy record of environmental change in Moreton Bay spanning from 1942 to the present. Cores of a Plesiastrea versipora from Peel Island and a Favia speciosa from Goat and Peel Island were collected on the 28/6/2011. A core sample of a Favia speciosa collected from Wellington Point in 1997 and a fossil of the same species from Cleveland Point were also incorporated into this study. Trends in trace metals (Mn, Zn, Sn, Cu, Fe, Pb, rare earth elements, and yttrium concentrations (La Ce Pr Nd Sm Eu Gd Tb Dy Ho Er Tm Yb Lu and Y) were measured, with chronologies developed from X-­ray densitometry and U-­Th dating. Annual trends in metal concentration were highly variable, with few long-­term trends. Comparisons of rare earth elements and yttrium (REY) concentrations in coral cores from western and eastern Moreton Bay indicated a strong terrestrial-­marine environmental gradient characterized by hypo-­saline turbid waters in western Moreton Bay at Wellington Point to more oceanic water in eastern Moreton Bay at Peel and Goat Island. Decadal REY oscillations measured in P. versipora where predominantly driven by rainfall variation in the Brisbane river catchment, resulting in decadal trends of decreased river influence in southern Moreton Bay between 1942 and 2011. Completion of Wivenhoe Dam in the upper Brisbane river catchment in 1981 resulted in a decrease in discharge variability of the Brisbane River. This is shown in a drop in total REY concentrations in modern corals of Eastern Moreton Bay. Sea level rise is also discussed as potential driver of this decrease. Mid-­Holocene (6ka) Cleveland point was characterized by high river influence comparable with modern Wellington point, but with less environmental variability through time. This study highlights the strong environmental gradients in the bay, driven by tidal currents and catchment process, and their possible interaction with biological aspects of the Bay, including the potential for localized coral growth.

## Marie Mauffrey

[marie_a03@hotmail.com](mailto:marie_a03@hotmail.com)

*Density measurements and calculation of calcification of Goniopora spp. using CT-scan 3D modelization*

This study presents a long term record of calcification of Goniopora from the Great Barrier Reef and reveals that calcification rate has been declining for the past 700 years. The significant decrease observed in the mid 19th century corresponds to the European settlement as well as the end of the Little Ice Age. Before this breaking point, calcification is driven by sea surface temperature showing an inverse relationship trend. It is possible that the effect of European settlement on calcification could be explained among other by sedimentation and river discharge. Also the end of the LIA announced drastic changes in temperature. This period is a transition between a cold period and global warming. However the response of corals is still to discover yet.

## Danika Tager

Reef ecosystems built during successive periods of Pleistocene sea level rise have shown remarkable persistence in coral community structure, but little is known of the ecological characteristics of reef communities during periods of low sea stands or sea level falls. We sampled the relative species abundance of coral, benthic foraminifera, and calcareous red algae communities from eight submerged coral reefs in the Huon Gulf, Papua New Guinea, which formed during successive sea level fall and lowstand periods over the past ;416 kyr. We found that dissimilarity in coral species composition increased significantly with increasing time between reef-building events. However, neither coral diversity nor the taxonomic composition of benthic foraminifera and calcareous red algae assemblages varied significantly over time. The taxonomic composition of coral communities from lowstand reefs was significantly different from that of highstand reefs previously reported from the nearby Huon Peninsula. We interpret the community composition and temporal dynamics of lowstand reefs as a result of shifting energy regimes in the Huon Gulf, and differences between low and highstand reefs as a result of differences in the interaction between biotic and environmental factors between the Huon Gulf and Huon Peninsula. Regardless of the exact processes driving these trends, our study represents the first glimpse into the ecological dynamics of coral reefs during low sea level stands when climatic conditions for reef growth were much different and less optimal than during previously studied highstand periods.

## Dean Blower

[dean.blower@uqconnect.edu.au](mailto:dean.blower@uqconnect.edu.au)

Despite the international and regional protection of white sharks (Carcharodon carcharias), measures fundamental to monitoring their conservation status, population size, genetic population structure and genetic diversity, have not been established. Tissue sourced from predominately juvenile white sharks of five Australian regions was sequenced for the mtDNA control region and genotyped with six nuclear-encoded microsatellite loci. Maternally inherited population structure was found between all regions, suggesting regional natal philopatry, and was also found between the east and south/west coasts, which concords with recent tracking data from satellite and acoustic tags, that indicates the presence of east coast white shark nurseries. Finding genetic population subdivision with both maternally and bi-parentally inherited markers suggests that both genders exhibit degrees of regional philopatry and that males are not panmictic as previously supposed. In contrast, five sharks captured on the east coast proved to have haplotypes that resemble western Indian Ocean sharks more closely than Australian and New Zealand sharks. Estimates of long-term genetic effective population size from microsatellite loci indicate that an extensive ancestral white shark population once existed. Contemporary estimates of genetic effective population size suggest a breeding population in Australian waters greater than commonly accepted thresholds for inbreeding and loss of adaptive potential. However, unmonitored population decline could expose these genetically populations isolated to precipitous loss of genetic diversity. Therefore, we suggest that the current level of international and regional protection of white sharks is appropriate but that populations should be investigated in more detail.

---